### PR TITLE
Add SpongeDocs License

### PR DESCRIPTION
**Pull request by Inscrutable**
This is supposed to resolve Issue #565. _In summary:_

## SpongeDocs does not currently have a license specified. We intend to correct this by applying the CC-BY-SA license to our documentation.

Re-licensing the Sponge Documentation requires every significant contributor to accept the new licensing arrangement, by either replying to this thread in the template form, or via email or PM to one of the Editorial staff. We have prepared a table of contributors we need consent from, and that will be added to this PR shortly. It can't be merged until full consent is attained anyway.

Here is the consent form template we want everyone to use:
> I, [developer name] [GitHub email(s)] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

The full CC-BY-SA license may be viewed [here](https://creativecommons.org/licenses/by-sa/4.0/legalcode). A copy of the license will also be added with this PR.

_We Apologise for the Inconvenience._

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by Tzky** [comment]
I, Tzky (prozac25@gmx.de tzk.forums@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Inscrutable** [comment]
I, Inscrutable (inscrutable@internode.on.net) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).
All Aboard!

**Comment by Tzky** [comment]
This is the list of current and past contributors on the SpongeDocs:

|      |Real Name                   |Github-Account    |E-Mail                                    | Comment
|----------------------|----------------------------|------------------|------------------------------------------|---------
|<ul><li>[ ] </li></ul>|12AwesomeMan34              |@12AwsomeMan34    |aaronlingerfelt@yahoo.com / awsomeman149@gmail.com |
|<ul><li>[ ] </li></ul>|Aaron Hill                  |@Aaron1011        |aa1ronham@gmail.com                       |
|<ul><li>[ ] </li></ul>|Andrew / Inscrutable        |@Inscrutable      |inscrutable@internode.on.net              |
|<ul><li>[ ] </li></ul>|Andrew                      |@unenergizer      |unenergizer@gmail.com                     |
|<ul><li>[ ] </li></ul>|bibo38                      |@bibo38           |bibo38@users.noreply.github.com           |
|<ul><li>[ ] </li></ul>|boformer                    |@boformer         |felix.free@gmx.de                         |
|<ul><li>[ ] </li></ul>|Bryce Browner               |@Brycey92         |Brycey92@users.noreply.github.com         |
|<ul><li>[ ] </li></ul>|Brynley McDonald            |@ZephireNZ        |brynleymcdonald@gmail.com                 |
|<ul><li>[ ] </li></ul>|Chris Darnell               |@cedeel           |chris@cedeel.com                          |
|<ul><li>[ ] </li></ul>|Chris Sanders               |@Zidane           |zidane@outlook.com                        |
|<ul><li>[ ] </li></ul>|Chris54721                  |@chris54721       |chris54721@outlook.com                    |
|<ul><li>[ ] </li></ul>|Christopher Schnick         |@Milchshakee      |c.schnick@monospark.org                   |
|<ul><li>[ ] </li></ul>|Corey Ling                  |@Kasuko           |coreyling@ionshard.com                    |
|<ul><li>[ ] </li></ul>|Daniel Ahn                  |@xNinjaKittyx     |sangbumahn@gmail.com                      |
|<ul><li>[ ] </li></ul>|Daniel Silva                |@Dannyps          |daniel_p_silva_97@hotmail.com             |
|<ul><li>[ ] </li></ul>|DanielRHarris               |@DanielRHarris    |daniel9harris@gmail.com                   |
|<ul><li>[ ] </li></ul>|David Kolb                  |@dkolb            |david.kolb@krinchan.com                   |
|<ul><li>[ ] </li></ul>|Dracomeister                |@Avarel           |dracomeisterat@gmail.com                  |
|<ul><li>[ ] </li></ul>|elfin8er                    |@elfin8er         |elfin8er@gmail.com                        |
|<ul><li>[ ] </li></ul>|FerusGrim                   |@FerusGrim        |ferusgrim@gmail.com                       |
|<ul><li>[ ] </li></ul>|Flibio                      |@Flibio           |flibio.business@gmail.com                 |
|<ul><li>[ ] </li></ul>|Gabriel Harris-Rouquette    |@gabizou          |gabizou@me.com                            |
|<ul><li>[ ] </li></ul>|gratimax                    |@maxov            |max@ovsankin.com                          |
|<ul><li>[ ] </li></ul>|hawtre                      |@hawtre           |hawtre@gmail.com                          |
|<ul><li>[ ] </li></ul>|Jack Stratton               |@phroa            |jack@phroa.net                            |
|<ul><li>[ ] </li></ul>|Jamie Mansfield             |@jamierocks       |jamie.mansfield.jm@gmail.com / lexwaresupport@outlook.com / lexwaresupport@outlook.com / malgm@lapis.blue |
|<ul><li>[ ] </li></ul>|JBYoshi                     |@JBYoshi          |JBYoshi@users.noreply.github.com          |
|<ul><li>[ ] </li></ul>|Jos Ahrens                  |@Zarthus          |BuuGhost@gmail.com                        |
|<ul><li>[ ] </li></ul>|Kiskae                      |@Kiskae           |kiskae@serverpeon.net                     |
|<ul><li>[ ] </li></ul>|Kodfod                      |@kodfod           |fodkod@gmail.com                          |
|<ul><li>[ ] </li></ul>|Latouth                     |@Latouth          |Latouth@users.noreply.github.com          |
|<ul><li>[ ] </li></ul>|Lemonous                    |@Lemonous         |andreasfriestad@yahoo.no                  |
|<ul><li>[ ] </li></ul>|Luke GB                     |@lukegb           |github@lukegb.com                         |
|<ul><li>[ ] </li></ul>|Maenni025                   |@Maenni025        |maenni025@gmx.de                          |
|<ul><li>[ ] </li></ul>|Magnus Leßmann aka. Mark332 |@MarkL4YG         |github@m-lessmann.de                      |
|<ul><li>[ ] </li></ul>|Malte                       |@Lergin           |lergin@gmx.de                             |
|<ul><li>[ ] </li></ul>|Max Ovsiankin               |@maxov            |max@ovsankin.com                          |
|<ul><li>[ ] </li></ul>|mbax                        |@mbax             |matt@phozop.net                           |
|<ul><li>[ ] </li></ul>|Michael Vorburger           |@vorburger        |mike@vorburger.ch                         |
|<ul><li>[ ] </li></ul>|Minecrell                   |@Minecrell        |dev@minecrell.net                         |
|<ul><li>[ ] </li></ul>|Mumfrey                     |@Mumfrey          |adam@eq2.co.uk                            |
|<ul><li>[ ] </li></ul>|Necrodoom                   |@necrodoom        |doomed.war@gmail.com                      |
|<ul><li>[ ] </li></ul>|Nick Condé                  |@Deamon5550       |nick@budgiehouse.com                      |
|<ul><li>[ ] </li></ul>|Patrick                     |@CoWinkKeyDinkInc |CoWinkKeyDinkInc@users.noreply.github.com |
|<ul><li>[ ] </li></ul>|Physika                     |@Owexz            |me@physika.me                             |
|<ul><li>[ ] </li></ul>|Progwml6                    |@progwml6         |progwml6@gmail.com                        |
|<ul><li>[ ] </li></ul>|RobertHerhold               |@RobertHerhold    |reherhold@gmail.com                       |
|<ul><li>[ ] </li></ul>|Ryan Leach                  |@ryantheleach     |rleach@rleach.id.au                       |
|<ul><li>[ ] </li></ul>|saladoc                     |@saladoc          |saladoc@heridan.de / saladoc@saladoc.de   |
|<ul><li>[ ] </li></ul>|sibomots                    |@sibomots         |sibomots@outlook.com                      |

**Comment by Tzky** [comment]
|        Response      |Real Name                   |Github-Account    |E-Mail                                    | Comment
|----------------------|----------------------------|------------------|------------------------------------------|---------
|<ul><li>[ ] </li></ul>|Simon816                    |@simon816         |simonbarnes1@googlemail.com               |
|<ul><li>[ ] </li></ul>|sk89q                       |@sk89q            |the.sk89q@gmail.com                       |
|<ul><li>[ ] </li></ul>|SKmedix                     |@skmedix          |skmedixs@gmail.com                        |
|<ul><li>[ ] </li></ul>|Starbuck Johnson            |@modwizcode       |starbuck@modwiz.com                       |
|<ul><li>[ ] </li></ul>|ST-DDT                      |@ST-DDT           |ST-DDT@gmx.de                             |
|<ul><li>[ ] </li></ul>|Steven Smith                |@blha303          |stevensmith.ome@gmail.com                 |
|<ul><li>[ ] </li></ul>|theboomer                   |@theboomer        |boomod@rogers.com                         |
|<ul><li>[ ] </li></ul>|ThinkChaos                  |@ThinkChaos       |ThinkChaos@users.noreply.github.com       |
|<ul><li>[ ] </li></ul>|Tux                         |@minecrafter      |write@imaginarycode.com                   |
|<ul><li>[ ] </li></ul>|Tyrannokapi                 |@tyrannokapi      |tyrannokapi@gmail.com                     |
|<ul><li>[x] </li></ul>|Tzky                        |@Tzky             |tzk.forums@gmail.com / prozac25@gmx.de    | consent
|<ul><li>[ ] </li></ul>|Walker Crouse               |@windy1           |walkercrouse@hotmail.com                  |
|<ul><li>[ ] </li></ul>|Marc Tellerva / Xemiru      |@Xemiru           |xemiruk@gmail.com / segavagrant@yahoo.com |
|<ul><li>[ ] </li></ul>|zml                         |@zml2008          |zml@aoeu.xyz                              |

**Comment by Tzky** [comment]
I, Tzky (prozac25@gmx.de tzk.forums@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by blha303** [comment]
I, Steven Smith stevensmith.ome@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Minecrell** [comment]
I, @Minecrell (dev@minecrell.net) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Deamon5550** [comment]
I, Nick Condé (nick@budgiehouse.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by ryantheleach** [comment]
I, Ryan Leach (ryantheleach) rleach@rleach.id.au agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by chris54721** [comment]
I, @chris54721 (chris54721@outlook.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by JBYoshi** [comment]
I, @JBYoshi (JBYoshi@users.noreply.github.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Lemonous** [comment]
I, Lemonous (andreasfriestad@yahoo.no), agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

- Andrew

**Comment by Lergin** [comment]
I, @Lergin [lergin@gmx.de] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Kiskae** [comment]
I, @Kiskae (kiskae@serverpeon.net) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by ST-DDT** [comment]
I, @ST-DDT (`ST-DDT @ gmx . de`) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by mbax** [comment]
I, @mbax (`matt @ ph oz op.net`) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by ST-DDT** [comment]
Pinging @pie-flavor as he also contributed. (after the collection of the contributor list)
Pinging @20zinnm as he has an open pull request.

**Comment by RobertHerhold** [comment]
I, Robert Herhold (reherhold@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by theboomer** [comment]
I, theboomer (boomod@rogers.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Zarthus** [comment]
I, Zarthus (buughost+sp@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Flibio** [comment]
I, Flibio (flibio.business@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by simon816** [comment]
I, @simon816 (simonbarnes1@googlemail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Aaron1011** [comment]
I, Aaron Hill (aa1ronham@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Kasuko** [comment]
I, Corey Ling (coreyling@ionshard.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by 12AwsomeMan34** [comment]
I, 12AwesomeMan34 (aaronlingerfelt@yahoo.com awsomeman149@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by skmedix** [comment]
I, @skmedix (skmedixs@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by xNinjaKittyx** [comment]
⁣I, xNinjaKittyx (sangbumahn@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Maenni025** [comment]
I, Maenni025 (maenni025@gmx.de) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Tzky** [comment]
I edited the emails on both lists. Sorry for causing any inconvenience!

**Comment by phroa** [comment]
I, Jack Stratton <jack+@phroa.net> agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by windy1** [comment]
I, Walker Crouse walkercrouse@hotmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by hawtre** [comment]
I, hawtre (hawtre@gmail.com) agree to the licensing of my existing and
future contributions to SpongeDocs under the Creative Commons Share-Alike
License (CC-BY-SA).

**Comment by minecrafter** [comment]
I, Tux (write@imaginarycode.com) agree to license my contributions under CC-BY-SA.On Feb 4, 2017 2:56 PM, hawtre <notifications@github.com> wrote:I, hawtre (hawtre@gmail.com) agree to the licensing of my existing and
future contributions to SpongeDocs under the Creative Commons Share-Alike
License (CC-BY-SA).

**Comment by pie-flavor** [comment]
I, Adam Spofford (pieflavor.mc@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by modwizcode** [comment]
My name is wrong on the list. It should be Iris Johnson, email `iris at modwiz dot com`. I, Iris Johnson (iris@modwiz.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Create Commons Share-Alike License (CC-BY-SA).

**Comment by Tzky** [comment]
@pie-flavor 
Added you to the list. Sorry for missing you.

@modwizcode 
Sure, corrected your name. Sorry for that one!

**Comment by necrodoom** [comment]
I, Necrodoom doomed.war@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by elfin8er** [comment]
I, elfin8er elfin8er@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by 20zinnm** [comment]
I, Meyer Zinn, hereby license my existing contributions and/or requested contributions to SpongeDocs under **the WTFPL** license.

I do not plan to make any future contributions at this time, but at a point where they might become relevant I will abide by the legal requirements.

Full license text:
```
        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
                    Version 2, December 2004 

 Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 

 Everyone is permitted to copy and distribute verbatim or modified 
 copies of this license document, and changing it is allowed as long 
 as the name is changed. 

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 

  0. You just DO WHAT THE FUCK YOU WANT TO.
```

**Comment by Inscrutable** [comment]
Redistribution and license change seems to be implicitly allowed in WTFPL, so we can take it and redistribute it under CC-BY-SA, and you get the bonus of attribution with our re-licensing.

**Comment by FerusGrim** [comment]
I, FerusGrim ferusgrim@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Brycey92** [comment]
I, Brycey92 (Brycey92@users.noreply.github.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by progwml6** [comment]
I, progwml6 [progwml6 + gm ai l. com] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Owexz** [comment]
I, Owen Bowdler (Physika) me@physika.me agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Xemiru** [comment]
I, Marc Tellerva xemiruk@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by 20zinnm** [comment]
@Inscrutable as I licensed my contributions under the WTFPL, I require no attribution. You or the project are free to use it without citation, it is essentially public domain.

**Comment by sk89q** [comment]
I, sk89q, the.sk89q@gmail.com, agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Inscrutable** [comment]
We want to have a consistent license @20zinnm so I'm using the same throughout where possible. Having a mix of licenses is not an acceptable solution. TBH the only citations are from the original commits anyway, and we aren't going to edit those.

**Comment by MarkL4YG** [comment]
I, Magnus Leßmann (@MarkL4YG) github@m-lessmann.de agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

---
I want to clearly specify that I consider all my open source contributions in my own or other repositories to be licensed under the [M.I.T.](https://opensource.org/licenses/MIT) license if not explicitly stated otherwise.

**Comment by jamierocks** [comment]
> We want to have a consistent license @20zinnm so I'm using the same throughout where possible. Having a mix of licenses is not an acceptable solution. TBH the only citations are from the original commits anyway, and we aren't going to edit those.

@Inscrutable What 20zinnm is trying to say is under the terms of the WTFPL, you are free to do as you wish with his contributions, eg re-licensing to CC BY-SA 4.0.

There is certainly some merit in doing this, such as being able to circumvent clause 3(a)(1)(B) `indicate if You modified the Licensed Material and retain an indication of any previous modifications; and` essentially state changes, for anybody wanting to use the contributions created by 20zinnm. Sub-licensing to other licenses than the rather permanent CC BY-SA could also be performed.

---

**I am not advocating the use of the WTFPL for the use of this project**
**This is NOT my agreement to re-licensing of my current contributions to the project, that will come later, when I have fully deliberated it.**

**Comment by Dannyps** [comment]
I, Dannyps, mail@dannyps.net daniel.s@outlook.pt, agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by dualspiral** [comment]
I, Daniel Naylor, git@drnaylor.co.uk, ([contributed via this commit](https://github.com/SpongePowered/SpongeDocs/commit/4d1ea4fde46a80e533ddcc15efec454bacd4c1cc)), agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by 12AwsomeMan34** [comment]
Updated the list. 24 consents left!

**Comment by DanielRHarris** [comment]
I, Daniel Harris, daniel9harris@gmail.com, agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by sibomots** [comment]
I, @sibomots, sibomots@mondolab.net, agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by vorburger** [comment]
I, Michael @vorburger mike@vorburger.ch mike + @ vo rb ur ger.ch _gladly_ agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Tzky** [comment]
Thanks for your support so far!

21 left, 5 of them are current SpongePowered staff.

**Comment by jamierocks** [comment]
I, Jamie Mansfield [the many emails listed above] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by saladoc** [comment]
I, Saladoc [both emails listed above] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by gabizou** [comment]
I, gabizou gabizou@me.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Latouth** [comment]
I, Latouth latouth@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by CoWinkKeyDinkInc** [comment]
I, @CoWinkKeyDinkInc [cowinkkeydinkinc@gmail.com](mailto:cowinkkeydinkinc@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by zml2008** [comment]
I, zml, zml at ao eu dot x yz, zac h at za chsthings dot co m agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Zidane** [comment]
I, Chris Sanders zidane@spongepowered.org agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by boformer** [comment]
Felix Schmidt (@boformer) also agrees to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

felix[dot]free[at]gmx[dot]de

**Comment by Milchshakee** [comment]
I, Christopher Schnick, c.schnick@monospark.org agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Tzky** [comment]
12 Contributors left.

**Comment by lukegb** [comment]
I, Luke Granger-Brown, `git(hub)?@lukegb.com`, agree to the licensing of my _existing_ contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by ZephireNZ** [comment]
I, Brynley McDonald, `brynleymcdonald@gmail.com` agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by bibo38** [comment]
I, bibo38 [email listed above] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Inscrutable** [comment]
Thank You to everyone who has already agreed, we're very grateful for your responses. 
It's two weeks since the License PR was launched, and there's only nine contributors left that we need to seek permission from. Most have also been messaged via email already, I'm hoping this bump reminds a few that we need their attention ...  Paging:

@unenergizer 
@cedeel 
@dkolb 
@Avarel 
@kodfod 
@maxov 
@Mumfrey 
@ThinkChaos 
@tyrannokapi

**Comment by feikname** [comment]
I, Flávio Monteiro (also known as feikname) (`flaviomonteiro2013@gmail.com`) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by kodfod** [comment]
I, Kodfod [fodkod@gmail.com] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Tzky** [comment]
8 left. Wooo

**Comment by tyrannokapi** [comment]
I, Tyrannokapi (tyrannokapi@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

(Apologies—just saw my name tagged in the most recent Sponge announcement.)

**Comment by maxov** [comment]
I, Max Ovsiankin (hello@maxov.me), agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by dkolb** [comment]
I, David Kolb (david.kolb@krinchan.com), agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Faegy** [comment]
I, Faegy (maximethiebaut@hotmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by ryantheleach** [comment]
The following was found by looking at the github contributors page.

@unenergizer 's commits.
https://github.com/SpongePowered/SpongeDocs/commit/9d5c9880fa69b8f63d75e1c04a5da2c5eb4ec4b1
https://github.com/SpongePowered/SpongeDocs/commit/64a572e7b8604afa44f09968dab9df55039eabee
https://github.com/SpongePowered/SpongeDocs/commit/265d51f55775c75df58ece9f105fc9a646d1e90d

@cedeel 's commits.
https://github.com/SpongePowered/SpongeDocs/commit/8e2ed5d465f7617380aee1a6028f5b6ee0d32812

@Avarel
Unable to find them mentioned on the github contributors page?

@Mumfrey 's commits
https://github.com/SpongePowered/SpongeDocs/commit/c16c213a1ff359986c8b6beede33b7e605a4dd7f
+ various images committed by others.

@ThinkChaos 's commits
https://github.com/SpongePowered/SpongeDocs/commit/81fb7ae64da38d6ffc69ce4eb30eb918a0054ee2

**Comment by Mumfrey** [comment]
I, Mumfrey [mumfrey at spongepowered dot org] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Avarel** [comment]
I, Dracomeister (dracomeisterat@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by Minecrell** [comment]
@phit You're missing above because you have contributed recently (after creation of this issue) in https://github.com/SpongePowered/SpongeDocs/pull/594. Would you mind approving the new license?

**Comment by phit** [comment]
I, phit (me@phit.link) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by RedNesto** [comment]
I, RedNesto(rednestomc@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by JonathanxD** [comment]
I, JonathanxD (aka TheRealBuggy) [joniweb01@gmail.com] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by EpicKnarvik97** [comment]
I, @EpicKnarvik97 (kristian.knarvik@knett.no) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by worm424** [comment]
I, worm424 worm424@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by CanOdope** [comment]
I, CanOdope [xCaleb.Bonnellx@gmail.com] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by MoeBoy76** [comment]
I, MoeBoy76(moeboy76@gmail.com) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by plenet10** [comment]
I, Plenet10 plenet10@gmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by 4lchemister** [comment]
I, [4lchemister] [pass2game@gmail.com] agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by pavog** [comment]
I, pavog (evilcodes [dot] dev [at] gmail [dot] com / paul [at] paulvogel [dot] me) agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by jacklin213** [comment]
I, jacklin213, agree to license all my contributions to SpongeDocs translations under CC BY-SA 4.0

**Comment by simon300000** [comment]
I, simon3000 simon3000@163.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by sweetcode** [comment]
I, Jan Krüger (jan@krueger-jan.de), agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by johnfg12** [comment]
I, johnfg12 j.gray26@hotmail.com agree to the licensing of my existing and future contributions to SpongeDocs under the Creative Commons Share-Alike License (CC-BY-SA).

**Comment by dualspiral** [comment]
For reference: the user @Johnfg10 and @johnfg12 are the same person: consent was indicated from #623 and comment above.

**Comment by JumpCricket** [comment]
I , JumpCricket agree to license all my contributions to SpongeDocs translations under CC BY-SA 4.0.

**Comment by ST-DDT** [comment]
Awesome

**Comment by CoWinkKeyDinkInc** [comment]
Finally merged lol

**Pull request merged**
