### PR TITLE
Update SpongeDocs to Java8

### PR DESCRIPTION
**Pull request by Tzky**
With the recent announcement that Sponge will (finally) move to Java8 and drop support for 6 and 7 the Docs now must get updated to fit Sponge.

ToDo-list i can currently think of:
- [x] check all code snippets for validity, modify where needed
 - [x] use Java Optionals instead of Guava
 - [x] remove import of Guava
- [x] state that Sponge needs Java8 to run
- [x] modify installation insctructions for JRE and JDK to require Java 8
- [ ] add instructions for Linux, where Java 8 sometimes isn't easily available

reference: 
https://forums.spongepowered.org/t/theres-a-java-update-available/9147
Issue:  #324

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by saladoc** [comment]
I've checked all code examples to be found within the plugins section.

Most don't even bother to list the `Optional` import so those are fine. I changed those who did import it and fixed other small errors where I spotted them.

**Comment by Tzky** [comment]
Alright, seems only the Linux instructions are missing to get this finished. At least for now...

**Comment by Inscrutable** [comment]
On the MC Wiki page [Setting up a server](http://minecraft.gamepedia.com/Tutorials/Setting_up_a_server) there is a section for Linux instructions, including getting Java 6 or 7 for many distros. This information could be adapted for our purposes, substituting 1.8 java versions.

**Comment by saladoc** [comment]
In the java 8 `Optional`, the method `absent()` does not exist and needs to be replaced with `empty()` Example occurence in `plugin/commands/arguments`:
```
Optional and weak arguments may return ``Optional.absent()``.
```
needs to be
```
Optional and weak arguments may return ``Optional.empty()``.
```

**Pull request merged**
