### PR TITLE
Condense contributing section

### PR DESCRIPTION
**Pull request by Tzky**
This PR cleans up the mess in /contributing/ leaving just a few pages
in.

This is achieved by removing old (empty) files, merging SpongeForge and
Vanilla into a single implementation page and replacing the Docs files
with a single page.

Comments and input on this is appreciated.

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by Tzky** [comment]
@gabizou will write up some docs on how to contribute to SpongeCommon. He suggested that his write-up should get pulled into the docs when done. This will probably affect this PR and the structure of the docs too.

Link: https://github.com/SpongePowered/SpongeCommon/wiki

**Comment by BlackGoat** [comment]
What happened to the 120-character limit guideline? #307 seems to be reverted somewhere... Better check #308 too. Something odd is going on here.

**Comment by Tzky** [comment]
Should be fixed now. I also added a temporary link to the SpongeCommon wiki, as long as it's not finished. Afaik we will pull that one in when it's done.

This should be ready for merging, too.

**Comment by RobertHerhold** [comment]
Looks good. Thanks for cleaning this up :)

**Pull request merged**
