### PR TITLE
Possible clarity on unapproved download links

### PR DESCRIPTION
**Pull request by mbax**
Looking for discussion.

### CODE REVIEW

**Review by kashike — APPROVED** [review]

**Comment by mbax** [comment]
> kashike approved these changes 2 minutes ago

> Looking for discussion.

:thinking:

**Comment by ryantheleach** [comment]
Reads much better this way.

**Comment by Inscrutable** [comment]
++Good.

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
The notion of the direkt download links is now gone. If that is not allowed like before it should explicitly be mentioned. But Im not sure how to express that properly.

**Comment by dualspiral** [comment]
I think that you need to make it explicit that you must have approved file links. I've added in bold where I've made changes.

Using the word "must" is stronger than "may", I would recommend that here because it indicates a harder rule.

**In addition to links to approved files**, you may link to the download pages of unapproved Ore file submissions but these links **must not be recommended over any approved submission by any means. This includes both explicitly marking a link to an unapproved file as recommended, or implicitly by making such links as or more prominent than links to approved builds**. Further, you **must** not attempt to circumvent any plugin warnings on Ore, including warnings that inform the user that a project has not yet been reviewed.

**Comment by mbax** [comment]
I like dualspiral's rewrite. :+1:

**Comment by Inscrutable** [comment]
Were you going to finish this up @mbax or would you like the editorial staff to splice in dualspiral's finely crafted alternate verbage?

**Review by ST-DDT — APPROVED** [review]

**Pull request merged**
