### PR TITLE
trying to fix #156

### LINKED ISSUE #156: Granite merger cleanup
Adding Granite to the mix means some pages must change. Here are the ones I could identify, there may be more I missed. Minor changes in wording are needed in most cases. 

    Index - add fourth component (Granite) - **DONE**
    about/FAQ - There were Downloads (of Granite), etc - **DONE**
    Add /contributing/granite folder and files
    server/getting-started/migrating/forge
    server/getting-started/launch-script
    server/getting-started/installation
    server/management/plugins (Granite vs Forge)
    downloads *
    changelog  *
* It is possible that some of these might need to become two pages, depending on what happens to Granite forums and where its' downloads end up.

### PR DESCRIPTION
**Pull request by Tzky**
Renaming Granite to Spongevanilla.

### CODE REVIEW

**Comment by boformer** [comment]
```
:( ERRORS (These are causing your build to fail):

/home/travis/build/SpongePowered/SpongeDocs/source/server/getting-started/migrating/spongevanilla.rst:6: WARNING: Title underline too short.

Forge Mods in a SpongeVanilla Server
-----------------------------
```

**Comment by Tzky** [comment]
Looking into that while i add more content.

**Comment by BlackGoat** [comment]
This is great work, thank you! Please don't be disheartened by the following nitpicking ;)
A few minor issues I spotted: the porting page ends in "so as well", remove the "so".
Can those video tuts in vanilla/index can be applied to building SpongeVanilla? We might want to ask @Mumfrey and @gabizou about that.
In vanilla/git.rst, the workspace should be SpongeVanilla not just Sponge.
Please be consistent with the capitalisation of coremod (ie. not Coremod, in downloads).
Finally, "Glowstone is a completely from the ground up rewritten Minecraft Server" would be more meaningful as ..."is a third-party open-source Minecraft server written from the ground up, independent of any Mojang code."

**Comment by Mumfrey** [comment]
> Can those video tuts in vanilla/index can be applied to building SpongeVanilla? We might want to ask @Mumfrey and @gabizou about that.

No, in fact since the merger the tutorials are actually wrong and need to be re-done from scratch :(

**Comment by Tzky** [comment]
Fixed.
So the tutorials should be removed completely?

**Comment by Tzky** [comment]
Well. Now the mess is perfect, but i hope we're good to go.

**Pull request merged**
