### PR TITLE
Expand debugging page. Fixes #260

### LINKED ISSUE #260: Debugging skipping steps.
https://docs.spongepowered.org/en/plugin/advanced/debugging.html#intellij Says Open the Sponge(Vanilla) project.

This implies that the Sponge(Vanilla) project has already been downloaded from the git repository and loaded into IntelliJ by this point. In my opinion this is skipping several steps that should be listed, as well as how to import the project.

### PR DESCRIPTION
**Pull request by saladoc**
- link to instructions for importing Sponge as a Project
 - Included missing steps
 - Brief breakpoint explanation
 - hopefully more clarity through more verbose explanations

Please review for clarity, and I need someone who uses IDEA to double-check the IntelliJ IDEA instructions

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by boformer** [comment]
Looks good to me. But I'm also not using IntelliJ

**Comment by gdude2002** [comment]
This is pretty inaccurate. Here's what you want to tell people to do.

* Open IntelliJ IDEA.
* Click Create New Project.
* Select Gradle in the popup, and click Next.
* Enter your Group ID, Artifact ID, and Version.
    * Your Group ID should correspond to your organization name, or something similar.
    * Your Artifact ID should correspond to your project name.
    * Your Version is up to you.
* Click Next twice, name your project, and click Finish.
* Head to the [Sponge API Dependencies page](https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/90088517/plugin/workspace/dependencies.html) and follow the instructions.
* In the Gradle tab to the right of the editor, click on the circular blue arrows (I don't have a better way to explain that, but here it is:  - It will refresh your project's dependencies and make them available to the IDE)

At that point, it's ready to go.

**Comment by gdude2002** [comment]
As for debugging..

Should warn people that they need to clone with `--recursive` to get all the submodules, as the IDE will fail to open the project upon missing gradle files and it could be confusing as to why it's missing. Could save you guys a lot of tickets.

> Open the Sponge(Vanilla) project.

Be more specific - you want them to open the build.gradle in the dialog rather than the directory itself. Maybe also mention that it will take some time for it to pull down all the dependencies and stuff. You can shunt the process into the background, but you won't see any directories in the project view until it's done.

> * Click Modules.
> * Click the Green + symbol (Add), and select Module Dependency



Yeah, gonna want to be more specific.

* Click Modules.
* Make sure "Sponge" is selected in the middle column, and click on the "Dependencies" tab.
* Click the green "Add" button **on the right** and select "Module dependency"
* Select your Module..

That's all I can see. I've tested it, and it works. Not bad!

**Pull request merged**
