### PR TITLE
Quickfixes

### PR DESCRIPTION
**Pull request by tyrannokapi**
This fixes a couple minor issues that have been mentioned:

* The text under "Preparing for Development" was poorly worded for translatability
* The bullets on the Implementations page were improperly formatted

I would like for this PR to stay open for a couple days in case of any other minor errors, so I suppose it could use a WIP label.

### CODE REVIEW

**Comment by Tzky** [comment]
On the index page, section "preparing for development":
"Contributing to Sponge." should be  "Contributing to Sponge". 

Its just a small change, so i assume it belongs here. Changing “Creating Plugins” and “Contributing to Sponge" to wirking links might be a solution too.

**Comment by tyrannokapi** [comment]
Yes, you are correct about the period. I think that linking to the appropriate section is a good solution.

The comma before the conjunction in a list is grammatically correct, at least in the US. I believe it is referred to as an Oxford comma. The US may be in the minority with this usage, though... @BlackGoat, do you have a preference on this?

**Comment by Dannyps** [comment]
[The Wikipedia article about the comma](https://en.wikipedia.org/wiki/Serial_comma).

btw, in [this page](https://github.com/SpongePowered/SpongeDocs/blob/master/source/server/getting-started/installation.rst), there's another period out of place. A quick search in Crowdin revealed that these are the only two case in which this happens, so, there shouldn't be any other string with this problem.

**Comment by BlackGoat** [comment]
Being Australian, I tend to favour UK grammar and spelling. Also from Wiki: "The Oxford comma tends not to be used in non-academic publications unless its absence produces ambiguity.". I prefer this fuzzy line - leave it out unless it looks weird (or is easily misinterpreted).

**Comment by BlackGoat** [comment]
Dannyps also spotted this: In the new FAQ, titles are not in Title Case

**Comment by Dannyps** [comment]
in PR #151 there are two sentences that are a bit odd IMO.


**"A full list of staff members may be located at :doc:`staff`."**
could be perhaps:
 - "A full list of staff members **is located** at :doc:`staff`."
 - "A full list of staff members **can be found** at :doc:`staff`."

and

**"This means that server owners run Sponge plugins on any implementation of the Sponge API..."**
laks something... It could be:
 - "This means that server owners **can** run Sponge plugins on any implementation of the Sponge API..."

both strings are from the file 'source/about/introduction.rst'.

I don't know if this PR can be used to correct these problems, but I'll leave them here anyway.

**Comment by tyrannokapi** [comment]
I'll correct those. Thanks.

**Comment by tyrannokapi** [comment]
I believe this is ready.

**Pull request merged**
