### PR TITLE
Normalize faq.rst by the SpongeDocs style guide.

### PR DESCRIPTION
**Pull request by Zarthus**
Fixes some inconsistent casing, remove a duplicate heading, and reword some titles to make more sense.

### CODE REVIEW

**Comment by RobertHerhold** [comment]
I think "Can I Create Client Side Mods With Sponge?" would suffice.

**Comment by RobertHerhold** [comment]
Also I think "Are There Downloads Available?" could be better stated as "Are Downloads Available?".

**Comment by RobertHerhold** [comment]
Whoops! I meant "Partitioned" as an actual substitution for "Broken Down". I'll fix it when I get back from vacation.

**Comment by Zarthus** [comment]
ah, I see now. It's not very significant luckily. ^^

**Comment by RobertHerhold** [comment]
@Zarthus It's fine; I just fixed it

**Pull request merged**
