### PR TITLE
Git fu

### PR DESCRIPTION
**Pull request by sibomots**
WIP

Going to document all the appropriate ```git-fu``` tricks and tips that make using git with Sponge painless.

Next ideas are to deal with squash, rebasing, merging to branch, merging to master, preparing branch prior to PR closure, etc..

### CODE REVIEW

**Comment by boformer** [comment]
I think git is also useful for plugin development. Why don't you make a general tutorial, and specific pages for api/forge linking to it?

**Comment by gratimax** [comment]
I'm going to leave these here, because they are pretty useful https://try.github.io/levels/1/challenges/1 http://onlywei.github.io/explain-git-with-d3/

**Comment by sibomots** [comment]
I agree that a general git document would be useful.  I also suggest that in the near term the documentation cover how to deal with Sponge and SpongeAPI contributions would have the best impact now.   Of course a general "Sponge Plugin + git" primer would be a close second on the list.

Good suggestion @boformer.

**Comment by BlackGoat** [comment]
The title 'Git-Fu' may be problematic, as it isn't very descriptive and TOCs will use it. May I respectfully suggest using a longer, more boring name for it? 
This may fit into a broader category of Git docs, *if* there are to be more pages. Have you decided how to structure them? (Maybe listed in the yet-to-be-created Git page to go in the yet-to-be-created tools folder). Finally, have you finished polishing this PR, @sibomots ?

**Comment by sibomots** [comment]
Agreed re: git-gu
/me has dejected look that he will not be a Dragon Warrior

Re: scheduler, yes. Merge.

Thx

Sent from my Windows Phone
________________________________

**Pull request merged**
