### PR TITLE
Create persistence.rst

### PR DESCRIPTION
**Pull request by BlackGoat**
Work in progress, based on the PR text by gabizou (Sponge API #272)

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by gabizou** [comment]
@BlackGoat Please note that `@SerializableAs` was removed from the Persistence API, and there is a [2nd Persistence API Expansion](https://github.com/SpongePowered/SpongeAPI/pull/481) that added the remainder of needed functionality. But many thanks for writing up documentation :smile:

**Comment by BlackGoat** [comment]
@gabizou Thanks for the feedback. That 2nd Persistence PR has a lot less text we can use here, and will need serious pruning and rewriting for users. Please go right ahead and correct, rearrange and append what I started here if you can.
Also, Travis currently fails the build because the 'default' html theme has been renamed to 'classic'... I'm not sure how to sort that out.

**Comment by gabizou** [comment]
> Also, Travis currently fails the build because the 'default' html theme has been renamed to 'classic'... I'm not sure how to sort that out.

Trust me, Travis has broken to the point that none of the API builds are working either :P When I get some time, I'll read over the Persistence docs and contribute where necessary.

**Comment by BlackGoat** [comment]
This is over a month old now, and a bit stale. It might be better to clean the slate and start again. Unless you want to fix this crusty relic @gabizou I'm going to close it.

**Comment by gabizou** [comment]
@BlackGoat Agreed, especially since Data API overhauled most of the examples provided. When I get a chance after writing implementation groundwork for common, i'll get around to writing docs for using persistence and data api.

**Pull request closed without merging**
