### PR TITLE
Ew GitHub for Windows <3 SourceTree

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by Tzky** [comment]
What about providing both on the docs? 
Decisions on software choices should be made by users not authors...

**Comment by gabizou** [comment]
Or, you know, could always just direct people to the [Git] website for downloads so they can have infinitely more options than we can advise.

[Git]:www.git-scm.com

**Comment by Zidane** [comment]
What @gabizou said.

**Comment by jamierocks** [comment]
I totally agree with directing people to the Git website, however I assumed a decision against that was made. :/

**Comment by ryantheleach** [comment]
Last time I used github for windows I struggled to do anything remotely useful or complex with it.

TortoiseGIT / GITgui / GIT / Sourcetree all at least give you more control, but my personal favourite is also SourceTree.

I don't really think we need git tutorials in the API, but at the same time I can imagine common scenario's that come up when developing with/for sponge that we should cover...

**Comment by gabizou** [comment]
I would just say "the Git website has a lot of documentation and provides plenty of options for GUI clients." We don't want to be providing git tutorials when there are so many out there, let alone that there is a substantial amount of documentation with using Git.

**Comment by BlackGoat** [comment]
Link to Git website added with explanation. Closing this.

**Pull request closed without merging**
