### PR TITLE
Global Config Properties Table

### LINKED ISSUE #289: Properties Table for global.conf needed
We should detail the sponge properties in a Table to allow translation of the Code block comments, and to generally resemble the adjacent server.properties page. Some might need small examples, such as the Alias feature, and some could benefit from a longer explanation (such as entity activation ranges). Renaming the docs page from sponge.conf to global.conf may also be a good idea.

### PR DESCRIPTION
**Pull request by BlackGoat**
Resolves #289

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/d22ed887/index.html.

Here are some links to the pages that were modified:

- modified https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/d22ed887/server/getting-started/configuration/sponge-conf.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/291#issuecomment-120597164), not to the direct url to the preview._

**Comment by RobertHerhold** [comment]
Why isn't 'sql' captitalized? It is an acronym

**Comment by BlackGoat** [comment]
I'll do that in the next edit. Still unsure what that 'enable' setting between the Minecraft animals and misc in Entity Activation Range does. Several animal mobs are missing from the list too, and I'm a little fuzzy on the meaning of the "infinite water" feature at the end.

**Comment by RobertHerhold** [comment]
Infinite water = Place two water buckets one block apart from each other (or in opposite corners of a 2x2), then they will fill in and create the other water source blocks. If disabled, it wouldn't create source blocks of water, but just the running water block from the existing sources.

**Pull request merged**
