### PR TITLE
Update Rec Java Version

### PR DESCRIPTION
**Pull request by BlackGoat**
This is about the best compromise I could come up with after input from Zidane, Mumfrey and progwml6. The wording may be wonky (and it is rather long), suggestions are welcome.
Made as a PR so we can all watch devs duel over preferred Java version :)

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/3de19e98/index.html.

Here are some links to the pages that were modified:

- modified https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/3de19e98/preparing/jdk.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/161#issuecomment-94478751), not to the direct url to the preview._

**Comment by Mumfrey** [comment]
It's really quite simple:

**Comment by zml2008** [comment]
@Mumfrey I love that you have flowcharts for everything

**Comment by Mumfrey** [comment]
> @Mumfrey I love that you **make** flowcharts for everything

FTFY :)

**Comment by zml2008** [comment]
That's an implementation detail :)

**Comment by Xemiru** [comment]
@Mumfrey where are you generating these charts from .c.

**Pull request merged**
