### PR TITLE
Unify documentation (no basic/advanced categories)

### PR DESCRIPTION
**Pull request by RobertHerhold**
After some discussion on IRC, it seems the general consensus is to get rid of the basic/advanced categories. This is for a few reasons:

* Topics end up getting written in two different places - part of the topic is in basics, and the other part is in advanced
* Examples in documentation are generally easy enough to follow that even 'advanced' topics can be used by beginner developers

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/index.html.

Here are some links to the pages that were modified:

- modified https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/index.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/blocks/accessing.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/blocks/concepts.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/blocks/index.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/blocks/modifying.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/blocks/tileentities.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/commands/arguments.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/commands/childcommands.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/commands/commandcallable.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/commands/creating.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/commands/index.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/commands/service.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/configuration/index.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/configuration/loaders.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/configuration/nodes.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/configuration/paths.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/configuration/values.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/database.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/debugging.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/entities/index.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/entities/spawning.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/events.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/injection.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/lifecycle.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/logging.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/main-class.html
- renamed https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/545d6eb4/plugin/manager.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/318#issuecomment-131149003), not to the direct url to the preview._

**Comment by BlackGoat** [comment]
One concern this leaves us with is the state of the Index of this section, which was already scarily long. I don't want any more nested folders if we can help it, but restructuring the layout so the page links are usefully grouped might help. Perhaps even a 2-column format (or table), to keep things in useful clusters rather than one long semi-random list... Suggestions wanted.

**Comment by Tzky** [comment]
I suggest another toc layout on the index page, maybe with grouped topics. Example:

Group1: link1 | link2 | link3
Group2: link4 | link5 | link6

^ this is somewhat how the Django docs do it.
Con: while the toc is automatically build (and will be hidden), this index must be maintained manually.

**Comment by RobertHerhold** [comment]
@BlackGoat 
Could you try to illustrate what you have in mind?

**Comment by BlackGoat** [comment]
To get where I as going to, two things need to be accomplished: 
(1) Group sets of plugin development docs together, into some logical categories.
     These might relate to complexity, or inter-relationships, or simply alphabetical order.
(2) Present these groups in a way that uses less screen real-estate, and is easier to navigate.
The present list of pages on the Index is uncomfortably long, and whist this is an acceptable default, I hope we can improve on this so things are easier to find for relatively inexperienced developers.
The method used in Django is a possibility, or we could even put the page links in tables.
However, I don't want to create any unnecessary complexity or re-add arcane categorisation. It really needs a developer's brain to sort out how we *might* do this.

Also, rather than completely derail this PR, it seems OK. Hopefully we won't have to shuffle these pages around ever again.

**Pull request merged**
