### PR TITLE
Fixed build issues

### PR DESCRIPTION
**Pull request by mosemister**

### CODE REVIEW

**Comment by ST-DDT** [comment]
I get the following error when running gulp:

````txt
[13:20:16] Using gulpfile ~\git\Minecraft\Sponge\SpongeDocs\gulpfile.js
[13:20:16] Starting 'default'...
[13:20:16] Starting 'build:dev'...
[13:20:16] Starting 'clean'...
[13:20:16] Finished 'clean' after 8.19 ms
[13:20:16] Starting 'sphinx:dev'...
Running Sphinx v4.5.0
loading translations [en]... done

Extension error:
Could not import extension sphinx.builders.epub3 (exception: No module named 'imghdr')
[13:20:16] 'sphinx:dev' errored after 509 ms
[13:20:16] Error in plugin "sphinx"
Message:
    Process failed with exit code 2
[13:20:16] 'build:dev' errored after 521 ms
[13:20:16] 'default' errored after 524 ms
````

**Comment by ST-DDT** [comment]
I tried re-installing python with different options and now I'm stuck with:

````txt
[13:25:47] Using gulpfile ~\git\Minecraft\Sponge\SpongeDocs\gulpfile.js
[13:25:47] Starting 'default'...
[13:25:47] Starting 'build:dev'...
[13:25:47] Starting 'clean'...
[13:25:47] Finished 'clean' after 8.34 ms
[13:25:47] Starting 'sphinx:dev'...
[13:25:47] 'sphinx:dev' errored after 5.57 ms
[13:25:47] Error in plugin "sphinx"
Message:
    spawn sphinx-build ENOENT
Details:
    errno: -4058
    code: ENOENT
    syscall: spawn sphinx-build
    path: sphinx-build
    spawnargs: source,build/dev/html

[13:25:47] 'build:dev' errored after 18 ms
[13:25:47] 'default' errored after 21 ms
````

**Comment by ST-DDT** [comment]
I still get an error:

````txt
[13:32:16] Using gulpfile ~\git\Minecraft\Sponge\SpongeDocs\gulpfile.js
[13:32:16] Starting 'default'...
[13:32:16] Starting 'build:dev'...
[13:32:16] Starting 'clean'...
[13:32:16] Finished 'clean' after 8.35 ms
[13:32:16] Starting 'sphinx:dev'...
[13:32:16] 'sphinx:dev' errored after 5.51 ms
[13:32:16] Error in plugin "sphinx"
Message:
    spawn sphinx-build ENOENT
Details:
    errno: -4058
    code: ENOENT
    syscall: spawn sphinx-build
    path: sphinx-build
    spawnargs: source,build/dev/html

[13:32:16] 'build:dev' errored after 18 ms
[13:32:16] 'default' errored after 21 ms
````

Any idea on how to debug it?

**Comment by mosemister** [comment]
Interesting. Ill take a look when i get some time :) hopefully it's just a simple fix i forgot to document

**Comment by mosemister** [comment]
> I still get an error:
> 
> ```
> [13:32:16] Using gulpfile ~\git\Minecraft\Sponge\SpongeDocs\gulpfile.js
> [13:32:16] Starting 'default'...
> [13:32:16] Starting 'build:dev'...
> [13:32:16] Starting 'clean'...
> [13:32:16] Finished 'clean' after 8.35 ms
> [13:32:16] Starting 'sphinx:dev'...
> [13:32:16] 'sphinx:dev' errored after 5.51 ms
> [13:32:16] Error in plugin "sphinx"
> Message:
>     spawn sphinx-build ENOENT
> Details:
>     errno: -4058
>     code: ENOENT
>     syscall: spawn sphinx-build
>     path: sphinx-build
>     spawnargs: source,build/dev/html
> 
> [13:32:16] 'build:dev' errored after 18 ms
> [13:32:16] 'default' errored after 21 ms
> ```
> 
> Any idea on how to debug it?

Just installed this branch on a fresh PC with no issues. Can I make sure the following?

- Your on this branch?
- You have followed the install steps 
> npm install -g gulp
> npm install
> pip install -r requirements.txt
> gulp

(the ``pip install`` being the part that has changed)

I saw on discord you were having git issues on discord, I tested with the latest git version (``git version 2.47.0.windows.1``) without any issues. Unsure whats going wrong there nor how to debug it

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
I got it working.
It might have been a strange combination of requiring admin permissions and imghdr getting removed in Python 3.13.

It works with python 3.12 when using elevated permissions.

**Pull request merged**
