### PR TITLE
Add guideline for maximum character line length

### PR DESCRIPTION
**Pull request by RobertHerhold**
This would be purely for the ease of writing the docs. It gets rather annoying to be scrolling side to side, so I think we should set a 120 (plus/minus) character line limit. What's the opinion on this?

@BlackGoat

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by BlackGoat** [comment]
RtD seems to be lacking any variable screen width options, so a maximum width is a good idea. Enforcing it for Tables may be more difficult. Code blocks might also violate this here and there. Perhaps they may be allowed exceptions?

**Comment by RobertHerhold** [comment]
I wouldn't mind for a few things like tables/code blocks, but I think in general there should be a general upper limit

**Comment by Tzky** [comment]
80 chars is the old limit which is rather low. I'd go with a number which fits to our docs theme. I suggest something like 100 to 120 chars.

Oh and i'd volunteer editing the docs to fit this rule.

**Comment by RobertHerhold** [comment]
@Tzky 
Thanks for offering, but I am pretty much finished with the reformatting

**Comment by RobertHerhold** [comment]
#308

**Pull request merged**
