### PR TITLE
Few bits of modifications here and there.

### PR DESCRIPTION
**Pull request by Xemiru**
Small bits and pieces of things that I've found can use improvement or correction.

### CODE REVIEW

**Comment by boformer** [comment]
Well done.

**Comment by simon816** [comment]
You really didn't need to make a new commit per file change, @BlackGoat IMO there should be a squash-your-commits policy

**Comment by Xemiru** [comment]
>i was using github to edit

**Comment by simon816** [comment]
Well the GitHub editor is very limited on features, you may want to see the suggested editors https://docs.spongepowered.org/en/workspace/text.html

Commits can be squashed by the person merging a PR, they do this in the other sponge repos.

**Comment by Xemiru** [comment]
ooh, pretty text editors.

odd how i didn't stumble upon this wandering the docs and making edits all over the places.
thanks.

**Comment by BlackGoat** [comment]
Title Case can be a bit wishy-washy. There are several conflicting definitions available, and frankly, it's not worth arguing about as long as we're consistent. 
As for squashing commits, it's not something I have much experience in. When I started out this was a Wiki. But next time I see 14 commits in a PR I'll request a bit of squashing.

**Comment by Xemiru** [comment]
well i finally figured out how to use Atom with git, so no need to worry about commit spam of small changes from my prs anymore

hopefully.

**Pull request merged**
