### PR TITLE
Change idea.rst to show steps...

### PR DESCRIPTION
**Pull request by Redrield**
...For using DemonWav's IntelliJ plugin to make a project.

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
I think think this should be added as a separate page. Simply because not everyone might want to use minecrqft development plugin

**Comment by Redrield** [comment]
Fair enough. I'll close this for now and open up a new one on a separate page

**Comment by RobertHerhold** [comment]
I don't believe this belongs in the Sponge documentation since this IntelliJ plugin is not endorsed or developed by Sponge. @Inscrutable please confirm

**Comment by Meronat** [comment]
Well I mean some Sponge developers have been working with the lead developer and the plugin is fairly useful. Once it gets out of alpha, maybe it would be a good choice to endorse it, as it does simplify the whole process a little and provides some small but nice features.

I don't think it should necessarily be the main or only way we should teach people how to set up their projects, but a nod towards it and a little guide wouldn't harm anyone.

**Pull request closed without merging**
