### PR TITLE
Github Actions Crowdin

### PR DESCRIPTION
**Pull request by felixoi**
This PR tries to setup a github action to upload source files to crowdin

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/8ce3e85/.

Here are some links to the pages that were modified:



_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/851#issuecomment-720106846), not to the direct url to the preview._

**Review by ST-DDT — APPROVED** [review]
It is somewhat confusing to not find the branch mentioned in the test runs, but I guess that was a safety measure during the tests.

I assume the name `CI` was chosen as a prelude to replacing all build runs with this file, wasn't it?
Maybe we should rename it to `main` in order to match the containing filename. Or is there a special reason to it?

**Comment by felixoi** [comment]
> It is somewhat confusing to not find the branch mentioned in the test runs, but I guess that was a safety measure during the tests.
> 
> I assume the name `CI` was chosen as a prelude to replacing all build runs with this file, wasn't it?
> Maybe we should rename it to `main` in order to match the containing filename. Or is there a special reason to it?

Renamed the workflow.
It's hard to test because GITHUB_REF does not contain the branch name when it's tested with a PR.

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
@felixoi There seems to be an issue with the crowdin job (stable) after merge.

**Comment by felixoi** [comment]
@ST-DDT I know. It maybe needs some more PR's because it's hard to test this branch specific stuff.

**Pull request merged**
