### PR TITLE
[WIP] Document custom data API

### PR DESCRIPTION
**Pull request by ST-DDT**
**SpongeDocs** | *SpongeAPI*

**Related issues:**
#335 , #436 , https://github.com/SpongePowered/SpongeAPI/issues/1913

Instead of waiting for the API to become ready, I might as well fix it myself.
This will be a long term project, so don't expect any quick progress.

If you have suggestions, go ahead. But don't review it yet.

### CODE REVIEW

**Comment by Inscrutable** [comment]
We now have a somewhat different beast to document. 
https://github.com/SpongePowered/SpongeAPI/commit/529dcce0f7254f136c5edca4dc3da46955be840d

**Comment by Inscrutable** [comment]
What's the status of this PR? Do we need to assemble an assault team for the task?

**Comment by ST-DDT** [comment]
I will revive this soon.

**Comment by ST-DDT** [comment]
I guess this one is obsolete now...

**Pull request closed without merging**
