### PR TITLE
Plugins shouldn't have Sponge in their name

### PR DESCRIPTION
**Pull request by Inscrutable**
We might want to include this as a note in the plugins section too.

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e65aaea7/index.html.

Here are some links to the pages that were modified:

- modified https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e65aaea7/about/rules.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/513#issuecomment-230081343), not to the direct url to the preview._

**Comment by RobertHerhold** [comment]
It should probably be enforced through Ore as well, rejecting plugins with "Sponge" in the name

**Comment by zml2008** [comment]
That's hard to do correctly -- what if the plugin actually deals with sponges the block in MC? Then a name containing Sponge could be totally appropriate.

**Comment by Inscrutable** [comment]
Indeed. The main reason I put this as a PR is to harvest opinions on what constitute exceptions. We generally don't want a plethora of third-party plugins with Sponge in the name, as it will confuse all sorts of folks. So far the exceptions seem to be:
* Ported Plugins with versions for other APIs
* Plugins dealing specifically with the minecraft block "Sponge". These will probably be few.

Are there any other reasonable exceptions anyone can think of?

**Comment by Inscrutable** [comment]
Suggested pages for extra mentions of this rule: _Plugin Identifiers_ and/or _Best Practices_.

**Pull request merged**
