### PR TITLE
Update Configurate documentation to reference Configurate wiki

### PR DESCRIPTION
**Pull request by zml2008**
This is mainly an effort to reduce duplication, and get rid of some wildly inaccurate information present on the Sponge documentation side. I've removed everything but Sponge-specific information from the configuration page and linked to the Configurate wiki.

I'd also appreciate if folks would give the Configurate wiki a readthrough/tweakup -- I kinda scribbled it up this morning and might have missed a few things.

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/4c6c0a86/index.html.

Here are some links to the pages that were modified:

- modified https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/4c6c0a86/plugin/basics/configuration.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/145#issuecomment-84735126), not to the direct url to the preview._

**Comment by BlackGoat** [comment]
Minor typo in last sentence: ary plugin => any plugin.

**Comment by BlackGoat** [comment]
Offloading the configurate docs to a third party site does save us work here at SpongeDocs, but has the disadvantage of not being translated by CrowdIn (unless you set up your own instance). Any translators have opinions on this? Also, may I ask, is this PR good to go now?

**Comment by Xemiru** [comment]
I'll have a shot at writing documentation for usage and translation in a few hours on a separate pr.

**Pull request merged**
