### PR TITLE
Make Migrating from Bukkit more clear

### PR DESCRIPTION
**Pull request by lexware**

### CODE REVIEW

**Comment by boformer** [comment]
I don't know how far the Pore project is, but a reference would be great.

**Comment by boformer** [comment]
https://github.com/LapisBlue/Pore

**Comment by lexware** [comment]
@boformer I didn't mention Pore because there are no publicly available builds, I didn't want to create confusion.

**Comment by BlackGoat** [comment]
The text looks rather cumbersome in English. How about
"No, unfortunately there is no native support for Bukkit plugins in Sponge. (It may be possible to re-implement the Bukkit API with a special Sponge plugin, and thus support Bukkit plugins, but this has not yet been demonstrated.)"

**Comment by lexware** [comment]
Ok, I will start to reword it, as a developer it made perfect sense.

—

**Pull request merged**
