### PR TITLE
Latest Staff Shuffle

### PR DESCRIPTION
**Pull request by Inscrutable**
Meronat, Vectrix & 2 Issue Wranglers added. 3 staff retired.

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by ryantheleach** [comment]
Was this pending for a reason @Inscrutable ? or were you looking for someone to just have a second pair of eyes over it?

**Comment by Inscrutable** [comment]
Mostly for informal review and comment. I don't mind if another editor merges it, as it means they read it. I suppose I should have tagged @Tzky just to be sure.

**Comment by ST-DDT** [comment]
Sorry

**Comment by ryantheleach** [comment]
Don't be sorry! You are a member, and judging by Inscrutables reply have sound judgement. I was just being careful because I've been paying closer attention to all pr's and tickets lately.

**Pull request merged**
