### PR TITLE
[WIP] Block API Docs

### PR DESCRIPTION
**Pull request by saladoc**
The already completed work to be commented on. Feedback and suggestions are appreciated.

To Do List:
 - [x] Accessing basic block data
 - [x] Modifying blocks / blockstates
 - [ ] Update existing stuff to be up to date with API changes
 - [ ] Accessing and modifying tile entity data
 - [ ] Working with snapshots
 - [ ] List of possible block properties (non-external)
 - [ ] Remove FLARD

### CODE REVIEW

**Comment by BlackGoat** [comment]
This has gone a bit quiet. Will there be more forthcoming, or should I merge it, @saladoc ?

**Comment by Deamon5550** [comment]
This has references to `BlockLoc` which was merged in to Location (and some things to Extent/World) a short while ago. Additionally several of the block properties are now represented via the Data API.

**Comment by saladoc** [comment]
@BlackGoat I have not had much time recently, but I shall update this as soon as I can. I expect that I can catch up on the API changes the beginning of next week and aim to get this updated until the weekend after.

**Comment by saladoc** [comment]
Closing in favor of #204 since I redid the whole thing.

**Comment by gabizou** [comment]
@saladoc Instead of closing the PR, why not just overwrite the branch with the new content?

**Comment by saladoc** [comment]
@gabizou i was not sure if that works when i deleted and re-forked my repository and I didnt want to abuse this for experiments...

**Pull request closed without merging**
