### PR TITLE
how to access and provide services

### PR DESCRIPTION
**Pull request by boformer**
Content is based on the javadoc and this status update:
https://forums.spongepowered.org/t/status-update-26-september-2014-api-developer-form/2859

### CODE REVIEW

**Comment by boformer** [comment]
maybe it would be better to use the EventManager instead of PermissionService in the first example?

The events page is linked to the services page:
https://docs.spongepowered.org/en/latest/plugins/event-bus/

**Comment by ryantheleach** [comment]
It should be whatever is expected to be more common or simple.

It should provide a clear example of how to get the common sponge provided services, but also contain an example of how to provide your own service based on your own or a third party interface (think vault for economy)

**Comment by boformer** [comment]
I added a simple example and replaced EventManager with PermissionService

**Comment by BlackGoat** [comment]
I haven't had any negative feedback from @sibomots so I'm going to merge this.

**Pull request merged**
