### PR TITLE
Improve Text API examples

### PR DESCRIPTION
**Pull request by RobertHerhold**
This pull request is a continuation of #191. The changes are:
* Rename all instances of "message" to "text" (where applicable, not a find and replace)
* Add examples for styled text (previously there was only colored text)
* Add an example for shortcut text construction using `Texts#of(Object... objects)`
* Rename messages.rst to text.rst (I can revert this if necessary)
* Remove Text creation from methods

### CODE REVIEW

**Comment by Minecrell** [comment]
Don't place text creation in a method, if it's the same every time you can simply store it in a constant

**Comment by RobertHerhold** [comment]
The previous examples had them in methods, so I was just continuing the trend

**Comment by Minecrell** [comment]
I never said the previous docs were perfect :P It's better to fix this now, creating methods with identical behavior every time is pretty much pointless, and Text is designed to be able to be stored in constants efficiently.

**Comment by RobertHerhold** [comment]
Sounds good :) I'll update them.

**Pull request merged**
