### PR TITLE
Document new SpongeGradle Ore Deploy plugin

### PR DESCRIPTION
**Pull request by Katrix**
Updated docs for Ore API V2. Let's try to actually get it merged this time.

Haven't actually updated the plugin itself yet, but this is what I want it to look like. Stuff to generate an API key is mostly final though.

Superseeds #589

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/301c6c9/.

Here are some links to the pages that were modified:

- added: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/301c6c9/ore/gradle-deploy.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/301c6c9/ore/index.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/799#issuecomment-493699973), not to the direct url to the preview._

**Comment by ST-DDT** [comment]
@Katrix What is the status of this PR?

**Comment by Katrix** [comment]
Waiting for 
1. The Ore API V2 to be released
2. The deploy plugin to be done and published

**Comment by ST-DDT** [comment]
@Katrix Is the API/plugin released yet?

**Comment by Katrix** [comment]
Nope, in fact tags are a bit in flux at the moment, so this PR might not be accurate to how we end up representing them in the end. Don't really know yet.

**Comment by Inscrutable** [comment]
This PR is so old it's almost starting to form sedimentary rocks. What's the status of this @Katrix - is there anything we can clean up and publish?

**Comment by Katrix** [comment]
We're not publishing anything that uses Ore APIv2 until that part is stable. Once we do, we can look at this

**Pull request closed without merging**
