### PR TITLE
Minor fixes ocd

### PR DESCRIPTION
**Pull request by Dannyps**
Addresses several issues defined in #437.

### CODE REVIEW

**Comment by Dannyps** [comment]
I solved all the issues to which I reacted with a  ❤️  :

**Comment by Inscrutable** [comment]
One question @Dannyps : it seems to be targeting ``SpongePowered:minor-fixes-ocd`` not ``SpongePowered:stable``. Is this intentional?

**Comment by ImMorpheus** [comment]
I've added dead link/redirect to the OCD list.

**Comment by Dannyps** [comment]
@Inscrutable It wasn't intentional. I forked `SpongePowered:minor-fixes-ocd` to prepare the PR, that's why I created it targeting that specific branch. Should I change to `SpongePowered:stable`? I believe it's possible.

**Comment by Inscrutable** [comment]
Hmmm. I'd prefer it went to the stable branch, unless you and @ST-DDT are planning an omnibus ocd-PR.

**Comment by ST-DDT** [comment]
Please target `stable`.

**Comment by Dannyps** [comment]
@Inscrutable, @ST-DDT, done!

**Comment by ST-DDT** [comment]
By changing the target you also took all the other commits from the other branch with you.
The easiest way to do this is to create a backup of your branch (with a different name), reset it to latest stable and then cherry pick your commits over.

**Comment by Dannyps** [comment]
I'm afraid I'm not very comfortable with PRs 😟
Would that require submitting a new Pull Request?

**Comment by ST-DDT** [comment]
No. It does not all you have to do is force pushing the fixed branch.
If you are not comfortable with it i can help you with it in roughly a week or two.

**Comment by Dannyps** [comment]
@ST-DDT I'd appreciate that, thank you.

**Comment by ST-DDT** [comment]
I fixed the commit history. If you need to make more adjustments make sure to use a clean/force pull before adding them. Old rev; https://github.com/Dannyps/SpongeDocs/commit/ee301cc01a99f2d2267961d6c6afd102767321d8

----------------------------------

Also I have seen that you reverted a commit because it causes the build to fail.
You can fix it be adding it to the imports at the top of the file like this:

````rst
.. javadoc-import::
	org.spongepowered.api.text.Text
	org.spongepowered.api.text.Text.Builder
	org.spongepowered.api.text.action.TextAction
````

If you need to attach a plural to those references you can do so using a backslash.

````rst
and :javadoc:`TextAction`\s.
````

-------------------------------

Anything else you would like to add/change?

**Comment by Dannyps** [comment]
Thank you, @ST-DDT! About that reverted commit, I'll correct it.

As for other stuff, I can't do much these days because of college. It'd probably be better if this could be merged when I done with that last fix, and we could have another PR like this somewhere in the future, to address new issues.

**Comment by Inscrutable** [comment]
Ummm, is this ready yet?

**Comment by Dannyps** [comment]
Nope, I'm still to fix that reverted commit. I believe I'll have that done in about 24h.

**Comment by Dannyps** [comment]
Replying to https://github.com/SpongePowered/SpongeDocs/pull/631#issuecomment-343765271
, and about fixing that plural, it looks like `:javadoc:*` doesn't support the `\s` terminology.

Examples: https://docs.spongepowered.org/stable/en/plugin/permissions.html#subject
(notice the `s` in `Players` is not part of the anchor)

I'll put it this way, but we should try to fix this in the future.

**Comment by Dannyps** [comment]
Should I open an issue addressing the the `\s` behaviour of `:javadoc:*`?

**Comment by ryantheleach** [comment]
The plural thing is a PITA, It's good as is IMO, it's only going to get twisted for the translations anyway.

**Pull request merged**
