### PR TITLE
Update message.rst, hocon.rst, and event-bus.rst

### PR DESCRIPTION
**Pull request by tyrannokapi**
* Updated source/plugins/message.rst as per #31 
* Updated source/users/hocon.rst as per #20 
* Fixed misspellings of "recipient" in source/plugins/event-bus.rst (formerly "receipient")

### CODE REVIEW

**Comment by ryantheleach** [comment]
Looks good, only thing that I would be concerned about is if sponge is actually going to use HOCON or not. there were talks of changing the ConfigAPI, but it may still end up using HOCON depending on the decision.

**Comment by tyrannokapi** [comment]
@ryantheleach Hmm, I wasn't aware of that. I suppose we'll just have to wait and see.

@boformer I believe the color is appended following the text, came across that when I was cross-referencing the forums. I could be wrong, though.

Thanks!

**Comment by ryantheleach** [comment]
@boformer https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/message/Messages.java#L56

Messages.builder("string") creates a new text builder, it's fine.

@tyrannokapi the color doesn't matter whether it's applied before or after the text as it is a single message segment. append creates a new text element and makes it a parent of the root message element.

The only thing really missing that I can see is translatable messages.

**Comment by boformer** [comment]
@ryantheleach I know what Messages.builder("string") does. the question is what messageBuilder.color(...) does.

**Comment by ryantheleach** [comment]
It adds a color component to the builder part representing that piece of text. It doesn't need to be at the front or the end it just works, in order to get multiple colors you need to nest multiple messages using append, unless they are arguments for a translatable message, in which case each argument is treated as a separate format-table message segment.

It's designed to be compatible with vanilla minecrafts json chat format described here: http://wiki.vg/Chat

**Pull request merged**
