### PR TITLE
[WIP] License clarification and rewrite code samples

### LINKED ISSUE #640: Outdated imports in docs
I checked the docs for imports that are no longer working with v6.0 and found these:

EDIT: (Removed outdated list)

The test tool to collect all used imports:

````java
public class ImportTest {

    private static Set<String> imports = new TreeSet<>();
    private static int i = 0;

    public static void main(String[] args) {
        File root = new File("../SpongeDocs/source");
        fileStream(root).forEach(ImportTest::test);
        imports.forEach(s -> System.out.println(s + " a" + i++ + " = null;"));
    }

    static Stream<File> fileStream(File file) {
        if (file.isDirectory()) {
            return Arrays.stream(file.listFiles()).flatMap(JavadocRefTest::fileStream);
        } else if (file.isFile() && file.getName().endsWith(".rst")) {
            return Stream.of(file);
        } else {
            return Stream.empty();
        }
    }

    static void test(File file) {
        try {
            Files.lines(file.toPath())
                    .dropWhile(Predicate.isEqual(".. javadoc-import::").negate())
                    .skip(1)
                    .takeWhile(Predicate.isEqual("").negate())
                    .map(String::trim)
                    .forEach(imports::add);
        } catch (IOException e) {}
    }
}
````

### PR DESCRIPTION
**Pull request by parlough**
I still have to rewrite most of the code samples but I have started setting up some of the changes and clarifying licenses. People can review as I go. 

In this PR I will also be updating other information as it stands in API 7.

Will address https://github.com/SpongePowered/SpongeDocs/issues/689 when finished.

This should also close https://github.com/SpongePowered/SpongeDocs/issues/640 and https://github.com/SpongePowered/SpongeDocs/issues/618

### CODE REVIEW

**Comment by parlough** [comment]
There's a long way to go, but @ST-DDT you should have push access if you ever have a chance to lend a hand. Don't really have a list to track what I've rewritten at the moment, but you can just look at files changed for now.

**Comment by parlough** [comment]
Will need to modify the theme a little bit once this is done to add MIT to the footer - https://github.com/SpongePowered/sponge-docs-theme/blob/master/src/theme/templates/footer.html

**Comment by Inscrutable** [comment]
There is also the possibility of using the Unlicense license for the code. http://unlicense.org/

**Comment by ST-DDT** [comment]
Please resolve merge conflicts.

**Comment by Inscrutable** [comment]
@parlough what has become of thee?

**Comment by ST-DDT** [comment]
@parlough Can we merge most of this in, so that it does not gather any more dust? AFAIK everything can be merged except for the code samples license.

If you want I can give you a helping hand and fix the merge conflicts for you, then you just have to select the parts that can be merged earlier.

**Comment by Inscrutable** [comment]
I'm afraid that @parlough has been unavailable/busy IRL for the last few months, so if you can clean this up @ST-DDT it would probably be the most expedient solution.

**Comment by ST-DDT** [comment]
Superseded by #773

**Pull request closed without merging**
