### PR TITLE
Update version references to 7.1.0

### PR DESCRIPTION
**Pull request by ST-DDT**
Updated all references in the docs from 7.0.0 to 7.1.0.

The following entries refer to a pre release version of the API 7.1.0. 
I'm not sure whether these files need to be updated.

* `/source/files/logs/SpongeForge_1.12.2-2705-7.1.0-BETA-3136_debug.log.txt`
* `/source/files/logs/SpongeForge_1.12.2-2705-7.1.0-BETA-3136_latest.log.txt`
* `/source/files/logs/SpongeVanilla_1.12.2-7.1.0-BETA-54_latest.log.txt`

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/.

Here are some links to the pages that were modified:

- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/ore/routes/deploy-version.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/ore/routes/list-versions.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/ore/routes/project-version.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/ore/routes/project.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/plugin/internals/implementation.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/plugin/internals/mcp-setup.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/plugin/project/gradle.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/plugin/project/index.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/plugin/project/maven.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/server/getting-started/configuration/sponge-conf.html
- modified: https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/e07d025/server/getting-started/implementations/spongeforge.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/765#issuecomment-419744849), not to the direct url to the preview._

**Review by Inscrutable — APPROVED** [review]
That covers all the bases.  For many of the these pages we only use the SpongeAPI version as an example anyway, so updating is just an optional courtesy. I presume we won't have to change the "stable-7" URLs on ``implementation/mixins``, ``plugin/commands/arguments`` and ``plugin/debugging`` until we get to API 8.

**Review by 12awsomeman34 — APPROVED** [review]
I do question whether we need those above mentioned pages on the docs? Regardless it may be worth updating them to see if anything has changed.

**Comment by Inscrutable** [comment]
The log pages *are* unnecessary, being only a courtesy. Updating them constantly may not be worth the effort, so if they fall by the way-side I won't complain. It might be better to feature in a separate PR though, as others may have different opinions.

**Pull request merged**
