### PR TITLE
Remove unnecessary space in SpongeAPI

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by RobertHerhold** [comment]
Please use #298, as @BlackGoat mentioned in #299

**Comment by jamierocks** [comment]
Too much effort :/

**Comment by RobertHerhold** [comment]
Sorry, but that was the decision that was made. Please bring it up with @BlackGoat if you would like to discuss it.

**Comment by BlackGoat** [comment]
There is no real rule here, more of a guideline. If it's already a PR, I'd just let it slide. I'm not that fussy. The point is, it should be easier to post them as comments, and let them all be wrapped up at once.

**Pull request closed without merging**
