### PR TITLE
Improve IntelliJ instructions

### PR DESCRIPTION
**Pull request by Tzky**
@gdude2002 suggested some changes/additions to intellij idea instructions here:
https://github.com/SpongePowered/SpongeDocs/pull/333#issuecomment-143293179

This PR changes the instructions to fit his suggestions.

### CODE REVIEW

**Comment by Spongy** [comment]
Setting up PR reference, please wait...

**Comment by Tzky** [comment]
@Inscrutable 
This PR should be done and can get merged when there are no further faults/issues. Thought you would like to have a final look at it.

**Comment by Inscrutable** [comment]
It makes as much sense to me as it's going to, and I can't see any obvious faults. Nice work. 
Does this also resolve #264 ?

**Comment by Tzky** [comment]
Copy-pasting our gradle file is a workaround. I havent tried to search the artifact yet. If you leave this open for now, i'll see if i can find a way to fetch the artifact.

**Pull request merged**
