### PR TITLE
Add link to a separate assets repository

### PR DESCRIPTION
**Pull request by Tzky**
Once the SpongeAssets repository becomes available to the public, this PR will adjust the Art Assets page to redirect users.

Solves #457

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/0ed2f190/index.html.

Here are some links to the pages that were modified:

- modified https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/0ed2f190/about/assets.html

_Since the preview frequently changes, please link to [this comment](https://github.com/SpongePowered/SpongeDocs/pull/470#issuecomment-201342886), not to the direct url to the preview._

**Comment by Tzky** [comment]
I'm not sure if we should keep the usage rules on the Docs or not as they'd better fit on the new assets repo.

Thoughts?

**Comment by Inscrutable** [comment]
The usage rules should get reviewed when the new repo is ready to go public, but I don't see the harm in having it reproduced. That way they will get translated, and if this is the staging point directing people there, then keeping them is still appropriate.

**Comment by Tzky** [comment]
Agreed. I'll keep them, but they must be updated before we pull this PR in.

We should also pull this PR into the static branches, not much extra effort, but keeps things clean.

**Comment by Inscrutable** [comment]
We need to determine what license we're using. I think it'll be Creative Commons (CC0) or possibly CC-ND (non-derivative) or even CC-NC (non-commercial). I'll let the overlords decide that one.

**Comment by 20zinnm** [comment]
Any update on this?

**Comment by Tzky** [comment]
We're still working out the details of the SpongeAssets repo. Afaik it's a private repo currently.

**Comment by Tzky** [comment]
Bump. With the relicensing of the docs currently in progress, we should get this resolved too. Are there any plans to get a repo up with all assets?

**Comment by Inscrutable** [comment]
This ancient PR needs a clean up if it's ever going to happen. 
The assets repo in the link does not exist, and in any case I think we should largely replace the contents of the page with excerpts from and a link to the Sponge Branding Manual. Anyone want to help here? Someone's arm needs to get twisted to get the manual formally approved, and I note that it's content is not quite in keeping with what the docs say at present. We also need to find or create new links to master graphics assets, if we're ever going to officially offer them.
Pinging the absent @Tzky

**Comment by kashike** [comment]
x

**Comment by Inscrutable** [comment]
This is currently a dead duck until @Mumfrey gives it some love. 
A new PR can get made when that eventually happens. Or ragnarok.

**Comment by ST-DDT** [comment]
I added most of the stuff from everything till https://github.com/SpongePowered/SpongeDocs/pull/470/commits/b898b28e67b29063b3bcbded88fbc7940d3d90f1 in #776

**Pull request closed without merging**
