### PR TITLE
Maintain consistency throughout the staff page

### PR DESCRIPTION
**Pull request by jamierocks**
If someone is the leader of multiple things: Community and IRC Leader.

If there are two unrelated things such as Web Leader and Developer - they should be on separate lines.

Also 'and' should be used and not '&'.

### CODE REVIEW

**Comment by RobertHerhold** [comment]
By that logic, why wouldn't Zidane's roles as "API Leader" and "LLC Director" be on two separate lines

**Comment by jamierocks** [comment]
Yes, he would. :P Fixing that now

thanks @RobertHerhold :)

**Comment by RobertHerhold** [comment]
Thank you :)

**Comment by jamierocks** [comment]
No problem :)

**Pull request merged**
