### PR TITLE
Fix typo descritption -> description in rawcommand.rst

### PR DESCRIPTION
**Pull request by JorelAli**
Fixes a typo in the Raw Command page where a variable was named `descritption` instead of `description`.

### CODE REVIEW

**Review by mosemister — APPROVED** [review]
Approved

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
I think our CI is broken.

**Comment by mosemister** [comment]
> I think our CI is broken.

It is. Has been for a while

**Comment by felixoi** [comment]
> It is. Has been for a while

It's versioning.. We would either need to upgrade sphinx or pin some dependencies (sphinx requires them but doesnt pin them, so pip just installs lastest..). Currently no time available for me to do that

**Pull request merged**
